language: rust
rust:
  - stable
sudo: false

cache: cargo

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

before_script:
  - pkg-config --libs libusb-1.0
  - pkg-config --modversion libusb-1.0

script:
  - cargo build --verbose
  - cargo test --verbose
